### ISSUE TITLE
SublimeLinter: error in SublimeLinter daemon:

### ISSUE THREAD

**Issue by tywrr** [Flet/SublimeLinter-contrib-standard#1]
jscs and jshint SublimeLinters are working fine but for some reason standard isn't. Standard is in my PATH as you can see and starts to lint but for some reason doesn't show anything on the GUI.

SublimeLinter: jscs version query: /Users/m467695/.nvm-fish/v0.12.0/bin/jscs --version 
SublimeLinter: jscs version: 1.11.3 
SublimeLinter: jscs: (>= 1.0.10) satisfied by 1.11.3 
SublimeLinter: jscs activated: /Users/m467695/.nvm-fish/v0.12.0/bin/jscs (disabled in settings) 
SublimeLinter: jshint version query: /Users/m467695/.nvm-fish/v0.12.0/bin/jshint --version 
SublimeLinter: jshint version: 2.6.0 
SublimeLinter: jshint: (>= 2.5.0) satisfied by 2.6.0 
SublimeLinter: jshint activated: /Users/m467695/.nvm-fish/v0.12.0/bin/jshint (disabled in settings) 
Emmet: No need to update PyV8
SublimeLinter: found existing HTML syntax, version 3 
SublimeLinter: found existing Rails syntax, version 1 
Package Control: Skipping automatic upgrade, last run at 2015-02-18 13:29:44, next run at 2015-02-18 14:29:44 or after
SublimeLinter: jscs version query: /Users/m467695/.nvm-fish/v0.12.0/bin/jscs --version 
SublimeLinter: jscs version: 1.11.3 
SublimeLinter: jscs: (>= 1.0.10) satisfied by 1.11.3 
SublimeLinter: jscs activated: /Users/m467695/.nvm-fish/v0.12.0/bin/jscs (disabled in settings) 
SublimeLinter: jshint version query: /Users/m467695/.nvm-fish/v0.12.0/bin/jshint --version 
SublimeLinter: jshint version: 2.6.0 
SublimeLinter: jshint: (>= 2.5.0) satisfied by 2.6.0 
SublimeLinter: jshint activated: /Users/m467695/.nvm-fish/v0.12.0/bin/jshint (disabled in settings) 
writing file /Users/m467695/Library/Application Support/Sublime Text 3/Packages/User/SublimeLinter.sublime-settings with encoding UTF-8 (atomic)
reloading Packages/User/SublimeLinter.sublime-settings
SublimeLinter: standard: _mainContentView.js ['/Users/m467695/.nvm-fish/v0.12.0/bin/standard', '--verbose'] 
SublimeLinter: standard output:
Error: Code style check failed:
  stdin:1:0: 'define' is not defined. (eslint/no-undef)
  stdin:11:3: Keyword "function" must be followed by whitespace. (eslint/space-after-keywords)
  stdin:11:83: Expected no padding newline after opening curly brace (jscs/disallowPaddingNewlinesInBlocks)
  stdin:13:15: Extra semicolon. (eslint/semi)

…..

  stdin:181:3: Extra semicolon. (eslint/semi) 
SublimeLinter: error in SublimeLinter daemon: 
SublimeLinter: -------------------- 
SublimeLinter: Traceback (most recent call last):
  File "/Users/m467695/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/queue.py", line 58, in loop
    item = self.q.get(block=True, timeout=self.MIN_DELAY)
  File "./queue.py", line 175, in get
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/m467695/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/queue.py", line 66, in loop
    self.lint(view_id, timestamp)
  File "/Users/m467695/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/queue.py", line 112, in lint
    self.callback(view_id, timestamp)
  File "/Users/m467695/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/sublimelinter.py", line 123, in lint
    Linter.lint_view(view, filename, code, hit_time, callback)
  File "/Users/m467695/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 917, in lint_view
    linter.lint(hit_time)
  File "/Users/m467695/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/node_linter.py", line 63, in lint
    is_dep = self.is_dependency()
  File "/Users/m467695/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/node_linter.py", line 88, in is_dependency
    is_dep = True if self.npm_name == pkg['name'] else False
KeyError: 'name'

SublimeLinter: --------------------

**Comment by feross** [comment]
Hmm, have you tried removing or disabling the jshint and jscs linters? Standard will take care of using those (or other linters) internally, so you don't need to install a linter for them. If you do, you might get conflicting or repeated messages.

**Comment by tywrr** [comment]
You can see in the console logs that I had them disabled but I tried removing them all together from Sublime so only have the 'standard' linter. 

What's interesting is it works in my other sublime project but not this one. Below is the error that happens, don't know how to interpret sublime's errors and not having any luck on google.
Also other linters work fine in this project.

reloading plugin Pretty JSON.PrettyJson
[Errno 2] No such file or directory: 'jq'
reloading plugin SublimeLinter-contrib-standard.linter
SublimeLinter: standard linter loaded 
reloading plugin Sublimerge Pro.Sublimerge
reloading plugin Vintageous.**init**
reloading plugin Vintageous.dev_cmds
reloading plugin Vintageous.ex_commands
reloading plugin Vintageous.ex_main
reloading plugin Vintageous.ex_motions
reloading plugin Vintageous.jump_list_cmds
reloading plugin Vintageous.modelines
reloading plugin Vintageous.state
reloading plugin Vintageous.test_runner
reloading plugin Vintageous.xactions
reloading plugin Vintageous.xmotions
reloading plugin Vintageous.xsupport
reloading plugin Vintageous.xsupport_mouse
reloading plugin Gutter Color.file
reloading plugin Gutter Color.gutter_color
reloading plugin Gutter Color.line
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.sublimelinter
plugins loaded
SublimeLinter: debug mode: on 
SublimeLinter: temp directory: /var/folders/1s/wdnjly0x2tq22yctcnz2qln877jpp6/T/SublimeLinter3-m467695 
SublimeLinter: found existing HTML syntax, version 3 
SublimeLinter: found existing Rails syntax, version 1 
Emmet: No need to update PyV8
Package Control: Skipping automatic upgrade, last run at 2015-02-18 16:02:26, next run at 2015-02-18 17:02:26 or after
writing file /Users/m467695/code/MobileCustomerAppUI/client/mcom/src/scripts/utils/tooltip.js with encoding UTF-8 (atomic)
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 256, in on_post_save
    callback.on_post_save(v)
  File "/Users/m467695/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/sublimelinter.py", line 445, in on_post_save
    self.file_was_saved(view)
  File "/Users/m467695/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/sublimelinter.py", line 470, in file_was_saved
    self.lint(vid)
  File "/Users/m467695/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/sublimelinter.py", line 123, in lint
    Linter.lint_view(view, filename, code, hit_time, callback)
  File "/Users/m467695/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/linter.py", line 917, in lint_view
    linter.lint(hit_time)
  File "/Users/m467695/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/node_linter.py", line 63, in lint
    is_dep = self.is_dependency()
  File "/Users/m467695/Library/Application Support/Sublime Text 3/Packages/SublimeLinter/lint/node_linter.py", line 88, in is_dependency
    is_dep = True if self.npm_name == pkg['name'] else False
KeyError: 'name'

**Comment by tywrr** [comment]
Figured it out. We didn't have a "name" attribute in package.json. Once added, it worked.

**Comment by feross** [comment]
ah, gotcha. that's interesting - glad it's working for you now!
