### ISSUE TITLE
Formatter design question

### ISSUE THREAD

**Issue by bcomnes** [Flet/SublimeLinter-contrib-standard#10]
Some auto-formatters use somewhat sophisticated format application strategies (eg js-beutifier and gosublime).  Any idea why they do that over just using self.view.replace()?

Examples:
- https://github.com/DisposaBoy/GoSublime/blob/eac47136dbca59b6923c9932b21752aa406cd12d/gosubl/gspatch.py
- https://github.com/enginespot/js-beautify-sublime/blob/master/jsbeautify.py#L189

**Comment by bcomnes** [comment]
Just a though... very large files with just a few errors might format quicker by calculating and applying a patch instead of a full overwrite?

**Comment by Flet** [comment]
Indeed, my take was purposely as simple and naive as possible just to get something working.

I'm fine with making it more intricate if its going to improve performance and give a better output.

I wonder how large is "very large". Maybe a litte perf test/compare is in order :)

**Comment by Flet** [comment]
Picking an absurdly large legacy .js file that is about 1400 lines:

```
time standard-format < bigfile.js


real    0m0.740s
user    0m0.468s
sys 0m0.332s
```

using `ctrl+alt+f` in sublime (adding a `time.time()` stopwatch with a print)

```
reloading plugin SublimeLinter-contrib-standard.format
1.78 seconds wall time
1.57 seconds wall time
1.69 seconds wall time
```

...So yeah some savings to be had I think!

**Comment by bcomnes** [comment]
I forgot to add, I had this auto formatter and my auto formatter turned on at the same time.  

:|

Performance was much closer when only one was turned on... At least perceivably.

**Comment by Flet** [comment]
Since I mentioned it too... here is jsformatter's code for design ref:
https://github.com/jdc0589/JsFormat/blob/master/js_formatter.py

**Comment by Flet** [comment]
Closing.. formatter stuff now at  [sublime-standard-format](https://github.com/bcomnes/sublime-standard-format)
