### ISSUE TITLE
not working with standard@3.2.0

### ISSUE THREAD

**Issue by feross** [Flet/SublimeLinter-contrib-standard#12]
Hey, does the command [here](https://github.com/Flet/SublimeLinter-contrib-standard/blob/master/linter.py#L21) assume that data is being passed in via stdin?

In standard@3.2.0 we [don't automatically detect stdin](https://github.com/feross/standard/commit/d7a98bceb86b258a93f8a97a172431c5d296306c) anymore, so I think this may have broken.

Can you change the command to `standard --stdin --verbose`?

**Comment by Flet** [comment]
Fixed in https://github.com/Flet/SublimeLinter-contrib-standard/commit/173a3c5de6803d0f26f3f76ee69001c614718e9f

New version should be on package control in about 30 minutes.

**Comment by feross** [comment]
Awesome, thanks!
