### ISSUE TITLE
SublimeLinter config question

### ISSUE THREAD

**Issue by gmaclennan** [Flet/SublimeLinter-contrib-standard#13]
This is probably a dumb question, but what is the best way to make SublimeLinter use standard on a module by module basis and not use jslint, eslint etc? I have jslint installed and use it for some projects, but am slowly converting some projects to js standard style. Is the best way to add `.sublimelinterrc` to the project root and disable other linters there?

**Comment by bcomnes** [comment]
I just disable the linter using the command palate as a shortcut for now.  Its not a thing that I'm aware of, but maybe we could research using some kind of code style field in `package.json` as a possible way to enable linters package by package.

**Comment by Flet** [comment]
Yeah, I will set it to disabled (and enable eslint usually) via the JSON under:
Preferences > Package Settings > SublimeLinter > Settings - User

But now I'm going to be doing it via command palate :)

I was not aware of [.sublimelinterrc settings](http://www.sublimelinter.com/en/latest/settings.html#sublimelinterrc-settings), but it looks to be a great way to handle this problem!

BTW, have you tried the auto-formatting shortcut that built in to this plugin? ctrl+alt+f  or type `format: JavaScript` in the command palate :)

**Comment by gmaclennan** [comment]
Thanks, that's useful. Yes, auto-formatting is great for switching libraries to Standard. A setting in package.json could be possible.

**Comment by Flet** [comment]
I think manually disabling/enabling via the command palette is going to be the most straightforward option here.. unless there is some new feature added to SublimeLinter itself.
