### ISSUE TITLE
Remove formatting options and add note to use StandardFormat

### ISSUE THREAD

**Issue by Flet** [Flet/SublimeLinter-contrib-standard#14]
Since @bcomnes now has [sublime-standard-format](https://github.com/bcomnes/sublime-standard-format) published to package control, we should remove the formatter from this plugin and add a note for users to install the StandardFormat if they want formatting.

**Comment by bcomnes** [comment]
Let's make sure to get windows working first before removing this.

**Comment by Flet** [comment]
Right on! once this is fixed we can do this: bcomnes/sublime-standard-format#7

**Comment by Flet** [comment]
Sounds like we're ready to do this now!

**Comment by bcomnes** [comment]
:+1: nice work @Flet thanks for the help :)  :beers:

**Comment by Flet** [comment]
You did the hard stuff @bcomnes :v:

**Comment by Flet** [comment]
Closed via https://github.com/Flet/SublimeLinter-contrib-standard/commit/ae58719372390e6115b63a64c31ba2b5658df4e6
