### ISSUE TITLE
Format not available in Command Palette

### ISSUE THREAD

**Issue by nifl** [Flet/SublimeLinter-contrib-standard#17]
I don't seem to have an option in the command palette for, "Format: JavaScript Standard Style". 

Otherwise, linter is working and errors are correct.

**Comment by Flet** [comment]
The formatting has been moved to a separate plugin now. Install `StandardFormat` from package control! It also has some other nifty things like "Format on Save"

> Install StandardFormat from package control!
> (https://github.com/bcomnes/sublime-standard-format)

**Comment by nifl** [comment]
Cool, things work now. Maybe update the readme unless I missed that. Thanks

**Comment by Flet** [comment]
Ah, looks like the README is out of date. I'll update it! :sunglasses:
