### ISSUE TITLE
updated didn't apply new rule validations?

### ISSUE THREAD

**Issue by gr2m** [Flet/SublimeLinter-contrib-standard#2]
I've updated standard to `2.10.0`, which introduced new rules, like `Missing space before function parentheses` also for anonymous functions.

But I don't see the error pop up in sublime. It is as if it still uses the old version? I've tried to re-install the SublimeLinter-contrib-standard and restart SUblime, didn't help.

```
$ $SHELL -l -c '/usr/bin/which standard'
/usr/local/bin/standard
$ /usr/local/bin/standard --version
2.10.0
```

Any idea? I don't know how to debug this farther ...

**Comment by feross** [comment]
Have you restarted sublime since upgrading `standard`?

**Comment by gr2m** [comment]
yes! But guess what, I just started to work?! Gnark sorry, seems good now :)

Just a quick question if you don't mind. When I manually run the linting with ctrl + command + l, hangs 1-2s, it feels pretty slow compared to JSHint for exmaple. Is it the same for you? Any idea?

**Comment by feross** [comment]
@gr2m Great to hear!

Yeah, we can definitely do better on speed. See https://github.com/feross/standard/issues/43. This will be fixed soon.

**Comment by gr2m** [comment]
ah great, thanks for the hint! Keep up the great work, much appreciated!
