### ISSUE TITLE
Doesn't seem to work with latest versions

### ISSUE THREAD

**Issue by zaynv** [Flet/SublimeLinter-contrib-standard#21]
Here are my current settings:

**node**: v6.0.0
**npm**: 3.8.8
**standard (global)**: 6.0.8
**standard (local)**: 6.0.8
**SublimeLinter-contrib-standard**: v3.1.0

However, no linter warnings come:

<img width="1392" alt="screen shot 2016-04-30 at 1 22 07 am" src="https://cloud.githubusercontent.com/assets/8627403/14934047/fc0c9a36-0e71-11e6-8ccc-b6e51482a1d5.png">

I have the linter enabled and I've tried using both On Save mode and Background mode for SublimeLinter.

If I run `standard index.js` or `./node_modules/standard/bin/cmd.js index.js`, I get the right output in the terminal.

Using the [StandardFormat](https://github.com/bcomnes/sublime-standard-format) package also seems to work fine within my editor as it automatically formats the code.

Thanks in advance for taking a look.

**Comment by mrhyde** [comment]
Exactly the same issue here, same versions. Can confirm that StandardFormat is working as well but SublimeLinter-Standard is not and have no idea why (no errors in console log)

**Comment by vslio** [comment]
Same issue here. As mentioned above, running `standard` on terminal works fine.

**node:** 6.0.0
**standard:** 7.0.0
**npm:** 3.8.6

**Comment by zaynv** [comment]
It seems to be working fine now. I would recommend you guys to try reinstalling `standard` with `npm install -g standard` (I currently have 7.0.1 installed) and then reinstall `SublimeLinter-contrib-standard` as well.
