### ISSUE TITLE
Package cannot be found 

### ISSUE THREAD

**Issue by 2color** [Flet/SublimeLinter-contrib-standard#25]
I can't find the package when searching for it. 

This is what I'm getting when searching standard.

Any reason why @Flet?

<img width="495" alt="screen shot 2016-06-21 at 10 08 04" src="https://cloud.githubusercontent.com/assets/1992255/16222450/5780b33a-3798-11e6-990c-5c964d32702f.png">

**Comment by Flet** [comment]
Strange! Works for me!

![std](https://cloud.githubusercontent.com/assets/360233/16242697/4bea09a6-37b9-11e6-8ffa-ac8b5bf6c276.gif)

Note that it will not show in the installed packages list if its already installed.
![installled](https://cloud.githubusercontent.com/assets/360233/16242727/77a359ee-37b9-11e6-8e65-d052d29690fe.gif)

**Comment by bcomnes** [comment]
Did you disable it with package control?  Did you disable it with sublimelinter? Those are the only reasons it should not be found in the install menu.

**Comment by 2color** [comment]
@bcomnes Yeah I did. 😵
