### ISSUE TITLE
Buggy behaviour for "custom" syntax

### ISSUE THREAD

**Issue by johannes-z** [Flet/SublimeLinter-contrib-standard#26]
I added a custom syntax vor vue templates (https://vuejs.org/) like so:

```python
syntax = ('javascript', 'html', 'javascriptnext', 'javascript 6to5', 'javascript (babel)', 'vue') # added 'vue'
...
selectors = {
    'html': 'source.js.embedded.html',
    'vue': 'source.js.embedded.html' # added vue selector
}
```

The linter throws one error and stop at it: `Parsing error: unexpected token : (null)`. The online interface to `standard` at http://standardjs.com/demo.html works perfectly with my code though.

Any ideas?

**Comment by johannes-z** [comment]
I got this working by updating the syntax with the official `HTML.sublime-syntax` for `script` tags.

**Comment by godbout** [comment]
@johannes-z any chance you remember what you did? I'm having the same problem and I don't understand what you're talking about 😅️

**Comment by johannes-z** [comment]
@godbout Hm not really... I guess I changed the settings so that the `script` tags are using the `HTML.sublime-syntax` instead... I can't remember however how you'd do that... sorry

**Comment by godbout** [comment]
@johannes-z alright no worries thanks. i've found a way that works correctly but not sure it'll do once i add some templating or css, but that's for another day.
