### ISSUE TITLE
Not showing in Package Control

### ISSUE THREAD

**Issue by bosbyj** [Flet/SublimeLinter-contrib-standard#27]
I don't know why, but at the moment it cannot be searched by Package Control within sublime.

Win8
ST Build 3126

`Package Contrl

The package 'SublimeLinter-contrib-standard' is not available`

**Comment by bcomnes** [comment]
https://packagecontrol.io/packages/SublimeLinter-contrib-standard ?

**Comment by bosbyj** [comment]
Maybe my package control isn't working fine. Just cannot find standard but semistandard is searchable.

![](http://i.imgur.com/LOzFwA3.png)

**Comment by bcomnes** [comment]
Super weird.  Did you possibly already install it on accident and not realize it?  I think that removes it from the installable list.  SublimeLinter has its own disable linter state that it keeps track of too, maybe look there too.

**Comment by Flet** [comment]
Working for me?
![image](https://cloud.githubusercontent.com/assets/360233/22908446/239145b2-f214-11e6-9f0f-2e5791aa3674.png)

Also I can confirm that it does not show up in the list if its already installed.

**Comment by bosbyj** [comment]
Thanks for all. Had no idea what happened. Because it didnt show up on the panel, I installed from source.

Maybe the package control of my ST3 was too old. I've been using 308x for a long while and accidentally updated to the latest version.

**Comment by Flet** [comment]
Closing this - hope things worked out!
