### ISSUE TITLE
Adding Standard JS Arguments to  SublimeLinter-contrib-standard

### ISSUE THREAD

**Issue by Fuchida** [Flet/SublimeLinter-contrib-standard#29]
I have these settings in Sublimelinter 

![image](https://user-images.githubusercontent.com/835396/29141539-3878a7e6-7d14-11e7-8ffa-95453a1676b4.png)

Yet I still get these 

![image](https://user-images.githubusercontent.com/835396/29141546-41bb7e64-7d14-11e7-8d5a-67ee7c77a84d.png)

Are the arguments not passed to StandardJS or am I doing it wrong ?

**Comment by frou** [comment]
`args` is an array, so shouldn't the 3 space-separated parts be split up?

**Comment by Fuchida** [comment]
from @frou response, that resolved my issue.
