### ISSUE TITLE
standard linter not applied: 'selector' is mandatory in 'cls.defaults'

### ISSUE THREAD

**Issue by m90** [Flet/SublimeLinter-contrib-standard#38]
Starting today (I have not done any upgrades or similar though), the standard linter stopped working in my setup. It is printing the following info to the console:

```
reloading plugin SublimeLinter-contrib-standard.linter
standard: Defining 'cls.syntax' has no effect anymore. Use http://www.sublimelinter.com/en/stable/linter_settings.html#selector instead.
standard: Defining 'cls.selectors' has no effect anymore. Use http://www.sublimelinter.com/en/stable/linter_settings.html#selector instead.
standard: Defining 'cls.version_args' has no effect. Please cleanup and remove these settings.
standard: Defining 'cls.version_re' has no effect. Please cleanup and remove these settings.
standard: Defining 'cls.version_requirement' has no effect. Please cleanup and remove these settings.
standard: Defining 'cls.npm_name' has no effect. Please cleanup and remove these settings.
standard disabled. 'selector' is mandatory in 'cls.defaults'.
 See http://www.sublimelinter.com/en/stable/linter_settings.html#selector
```

The versions I am using are SublimeLinter@4.12.0 and SublimeLinter-contrib-standard@3.1.3

I tried re-installing the packages, yet I will see the same behavior again. Other linters still apply, I do not use any custom settings overrides for the standard linter.

**Comment by ozgrozer** [comment]
Same here. All other linters working except Standard. Today I've noticed SublimeLinter has been upgraded. That might be the case.

**Comment by m90** [comment]
It looks like Sublime Linter 4.12.0 has been released today with the following notes:

```
SublimeLinter 4.12
==================

- Improved errors tooltip:
  Now wraps long lines
  Easily copy the error messages to you clipboard thanks to @kylebebak 💐

- Deprecations:
  We've previously pushed a number of deprecation warnings,
  those deprecations are now in full effect. Some new warnings
  (mostly for features you shouldn't be using anyway) have been
  added. Background info for plugin developers can be found
  here: https://github.com/SublimeLinter/SublimeLinter/pull/1613
  and:  https://github.com/SublimeLinter/SublimeLinter/milestone/7?closed=1
```

so maybe this is one of these deprecations that would previously log a warning, yet break as of today?

https://github.com/SublimeLinter/SublimeLinter/blob/master/messages/4.12.0.txt

**Comment by ozgrozer** [comment]
The way I fixed this issue:

1. Delete Sublime Linter package.
2. Install the previous version of Sublime Linter from source which is v4.11.3.

http://www.sublimelinter.com/en/v3.10.10/installation.html#installing-from-source
https://github.com/SublimeLinter/SublimeLinter/releases
