### ISSUE TITLE
Use user's PATH for format build command

### ISSUE THREAD

**Issue by feross** [Flet/SublimeLinter-contrib-standard#4]
When I use the COMMAND+B shortcut to build, `standard` is not found in my PATH. 

```
[Errno 2] No such file or directory: 'standard'
[cmd: ['standard', '--format', '/Users/feross/code/test/2.js']]
[dir: /Users/feross/code/test]
[path: /usr/bin:/bin:/usr/sbin:/sbin]
[Finished]
```

My actual PATH is `/Users/feross/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin` and if it was being used, `standard` would have been found. It works for linting.

**Comment by feross** [comment]
`/usr/local/bin` is a really common place for global npm installs to go. Maybe we can just add a `"path"` key to the `.sublime-build` file, and append `/usr/local/bin`:

``` json
{
    "cmd": ["standard", "--format", "$file"],
    "file_regex": "",
    "selector": "source.js",
    "path": "/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin"
}
```

documentation here: http://sublimetext.info/docs/en/reference/build_systems.html

**Comment by Flet** [comment]
This probaby breaks WIndows users. Also my global installs go to `/home/flet/npm/bin`.

I think this may be happening:

> On some operating systems, the value of PATH may vary between terminal windows and graphical applications. Thus, depending on how you start Sublime Text, the build system may or may not work.

http://docs.sublimetext.info/en/latest/reference/build_systems/troubleshooting.html#troubleshooting-build-systems

In any case, I think using the build system is a bit cheesy. The experience across systems/OSes was also a little different for me, where on one I had to hit F5 to get the changes to refresh in view.

**Comment by Flet** [comment]
Closing as the build system technique has been replaced.
