### ISSUE TITLE
Not possible to use standardx as executable

### ISSUE THREAD

**Issue by ivanbanov** [Flet/SublimeLinter-contrib-standard#41]
Im running the following config

```json
{
  "linters": {
    "standard": {
      "disable": false,
      "executable": "standardx",
      "excludes": ["node_modules"],
      "selector": "source.js, source.jsx"
    }
  }
}

```
but it doesnt use my executable :(

**Comment by ivanbanov** [comment]
Not sure if it's intended, anyway I opened a PR (#42) to "fix" it
Otherwise, if anyone else is having the same problem just use
```
{
  "linters": {
    "Standard": {  // camelised
      "disable": false,
      "executable": "standardx",
      "excludes": ["node_modules"],
      "selector": "source.js, source.jsx"
    }
  }
}
```

**Comment by bcomnes** [comment]
Thanks for the note, although I think fixing this would cause more disruption than its worth, given the inability of sublime plugins to push-out breaking changes in a way that doesn't just break everything.
