### ISSUE TITLE
Make formatting selections preserve indentation

### ISSUE THREAD

**Issue by Flet** [Flet/SublimeLinter-contrib-standard#8]
When selecting a chunk of text and running format, it sends that chunk of to `standard --format` as a single unit, so the formatter is removing all indentation.

This makes formatting selections of text a bit wonky if a subset of text in a block is formatted.

I wonder if its possible to use the previous lines indentation level to adjust the indentation after format.

**Comment by bcomnes** [comment]
Other implementations of js formatters support this but its ugly.  Still trying to sort the different approaches.

**Comment by Flet** [comment]
The `indent` branch here is my WIP attempt... Yeah I can see how it starts getting ugly.

**Comment by bcomnes** [comment]
I don't think I've ever uses selection formatting on purpose.  I was thinking about omitting it all together.  Thoughts?

**Comment by Flet** [comment]
I've used it myself with jsformatter plugin a bit... mostly to quickly fix indents in place without touching other parts of a file. Also ensuring only related code is modified instead of making a commit that mixes style fixes with specific code fixes.

Certainly a "nice to have" and not required.

**Comment by bcomnes** [comment]
Ok I'm cool with it.

**Comment by Flet** [comment]
If it gets annoying having to de-select to format all, we can always make it configurable.

**Comment by Flet** [comment]
Closing. Further discussion should happen at  [sublime-standard-format](https://github.com/bcomnes/sublime-standard-format)
